package personalloan;

//from row number: 1
//Approve
rule "Final Decision one"
	salience -2000
	lock-on-active false
	dialect "mvel"
	when
		$finalresult : FinalResult( app_xml_tu_status_id == null )
		exists (RuleResults( system_Decision == 1 )) 
		not (RuleResults( system_Decision in ( 2,3 ))) 
	then
		$finalresult.setApp_xml_tu_status_id( 1 );
end

//from row number: 2
//Refer
rule "Final Decision two"
	salience -2001
	lock-on-active false
	dialect "mvel"
	when
		$finalresult : FinalResult( app_xml_tu_status_id == null )
		exists (RuleResults( system_Decision == 3 )) 
		not (RuleResults( system_Decision in ( 2 ))) 
	then
		$finalresult.setApp_xml_tu_status_id( 3 );

end

//from row number: 3
//Reject
rule "Final Decision three"
	salience -2002
	lock-on-active false
	dialect "mvel"
	when
		$finalresult : FinalResult( app_xml_tu_status_id == null )
		exists (RuleResults( system_Decision == 2 )) 
	then
		$finalresult.setApp_xml_tu_status_id( 2 );

end

