package personalloan;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Applicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Integer applicant_education_qualification;

   private Double applicant_age;

   private char applicant_employment_is_permanent;

   private Integer applicant_total_work_ex;

   private Integer applicant_cibil_score_v2;

   private String applicant_dob;

   private java.lang.Double applicant_age_at_maturity;

   private java.lang.Integer applicant_company_category;

   private java.lang.Double applicant_income;

   private java.lang.Integer applicant_residential_status;

   private java.lang.Double applicant_foir;

   private Double applicant_cibil_total_obligations;

   private Double applicant_cibil_total_obligations_considered;

   private Double applicant_net_servicibility;

   @org.kie.api.definition.type.Label("applicant and  coapplicants both")
   private Double applicant_combined_net_monthly_income;

   private Double coapplicant_net_monthly_income;

   private java.lang.Double coapplicant_foir;

   private Double coapplicant_net_servicibility;

   private Double coapplicant_cibil_total_obligations_considered;

   private java.lang.Integer applicant_cibil_live_pl_accounts;

   private java.lang.Integer applicant_cibil_pl_inquiries;

   private java.lang.Integer applicant_company_industry_type;

   private Double applicant_abb;

   private java.util.List<java.lang.Integer> loan_multiplier_list;

   private java.lang.Integer applicant_residence_type;

   private java.lang.Integer applicant_pa_location_type;

   private java.lang.Integer applicant_cibil_live_track_pl_al_hl;

   private java.lang.Double applicant_max_age_allowed;

   private java.lang.Integer applicant_cibil_overdue;

   private java.util.Date test_date;

   private java.util.Date test_from_date;

   private java.lang.Integer applicant_cibil_total_inquiries;

   private java.lang.Integer applicant_cibil_writtenoff_accounts;

   private java.lang.Integer applicant_cibil_settled_accounts;

   private java.lang.Double applicant_cibil_settled_amount;

   private java.lang.Double applicant_cibil_writtenoff_amount;

   private java.lang.Double applicant_cibil_cc_outstanding_amount;

   public Applicant()
   {
   }

   public char getApplicant_employment_is_permanent()
   {
      return this.applicant_employment_is_permanent;
   }

   public void setApplicant_employment_is_permanent(
         char applicant_employment_is_permanent)
   {
      this.applicant_employment_is_permanent = applicant_employment_is_permanent;
   }

   public java.lang.Integer getApplicant_education_qualification()
   {
      return this.applicant_education_qualification;
   }

   public void setApplicant_education_qualification(
         java.lang.Integer applicant_education_qualification)
   {
      this.applicant_education_qualification = applicant_education_qualification;
   }

   public java.lang.Double getApplicant_age()
   {
      return this.applicant_age;
   }

   public void setApplicant_age(java.lang.Double applicant_age)
   {
      this.applicant_age = applicant_age;
   }

   public java.lang.String getApplicant_dob()
   {
      return this.applicant_dob;
   }

   public void setApplicant_dob(java.lang.String applicant_dob)
   {
      this.applicant_dob = applicant_dob;
   }

   public java.lang.Integer getApplicant_cibil_score_v2()
   {
      return this.applicant_cibil_score_v2;
   }

   public void setApplicant_cibil_score_v2(
         java.lang.Integer applicant_cibil_score_v2)
   {
      this.applicant_cibil_score_v2 = applicant_cibil_score_v2;
   }

   public java.lang.Integer getApplicant_total_work_ex()
   {
      return this.applicant_total_work_ex;
   }

   public void setApplicant_total_work_ex(java.lang.Integer applicant_total_work_ex)
   {
      this.applicant_total_work_ex = applicant_total_work_ex;
   }

   public java.lang.Double getApplicant_age_at_maturity()
   {
      return this.applicant_age_at_maturity;
   }

   public void setApplicant_age_at_maturity(
         java.lang.Double applicant_age_at_maturity)
   {
      this.applicant_age_at_maturity = applicant_age_at_maturity;
   }

   public java.lang.Integer getApplicant_company_category()
   {
      return this.applicant_company_category;
   }

   public void setApplicant_company_category(
         java.lang.Integer applicant_company_category)
   {
      this.applicant_company_category = applicant_company_category;
   }

   public java.lang.Double getApplicant_income()
   {
      return this.applicant_income;
   }

   public void setApplicant_income(java.lang.Double applicant_income)
   {
      this.applicant_income = applicant_income;
   }

   public java.lang.Integer getApplicant_residential_status()
   {
      return this.applicant_residential_status;
   }

   public void setApplicant_residential_status(
         java.lang.Integer applicant_residential_status)
   {
      this.applicant_residential_status = applicant_residential_status;
   }

   public java.lang.Double getApplicant_foir()
   {
      return this.applicant_foir;
   }

   public void setApplicant_foir(java.lang.Double applicant_foir)
   {
      this.applicant_foir = applicant_foir;
   }

   public java.lang.Double getCoapplicant_foir()
   {
      return this.coapplicant_foir;
   }

   public void setCoapplicant_foir(java.lang.Double coapplicant_foir)
   {
      this.coapplicant_foir = coapplicant_foir;
   }

   public java.lang.Integer getApplicant_cibil_live_pl_accounts()
   {
      return this.applicant_cibil_live_pl_accounts;
   }

   public void setApplicant_cibil_live_pl_accounts(
         java.lang.Integer applicant_cibil_live_pl_accounts)
   {
      this.applicant_cibil_live_pl_accounts = applicant_cibil_live_pl_accounts;
   }

   public java.lang.Integer getApplicant_cibil_pl_inquiries()
   {
      return this.applicant_cibil_pl_inquiries;
   }

   public void setApplicant_cibil_pl_inquiries(
         java.lang.Integer applicant_cibil_pl_inquiries)
   {
      this.applicant_cibil_pl_inquiries = applicant_cibil_pl_inquiries;
   }

   public java.lang.Integer getApplicant_company_industry_type()
   {
      return this.applicant_company_industry_type;
   }

   public void setApplicant_company_industry_type(
         java.lang.Integer applicant_company_industry_type)
   {
      this.applicant_company_industry_type = applicant_company_industry_type;
   }

   public java.lang.Double getApplicant_abb()
   {
      return this.applicant_abb;
   }

   public void setApplicant_abb(java.lang.Double applicant_abb)
   {
      this.applicant_abb = applicant_abb;
   }

   public java.lang.Double getApplicant_cibil_total_obligations()
   {
      return this.applicant_cibil_total_obligations;
   }

   public void setApplicant_cibil_total_obligations(
         java.lang.Double applicant_cibil_total_obligations)
   {
      this.applicant_cibil_total_obligations = applicant_cibil_total_obligations;
   }

   public java.lang.Double getApplicant_cibil_total_obligations_considered()
   {
      return this.applicant_cibil_total_obligations_considered;
   }

   public void setApplicant_cibil_total_obligations_considered(
         java.lang.Double applicant_cibil_total_obligations_considered)
   {
      this.applicant_cibil_total_obligations_considered = applicant_cibil_total_obligations_considered;
   }

   public java.lang.Double getApplicant_combined_net_monthly_income()
   {
      return this.applicant_combined_net_monthly_income;
   }

   public void setApplicant_combined_net_monthly_income(
         java.lang.Double applicant_combined_net_monthly_income)
   {
      this.applicant_combined_net_monthly_income = applicant_combined_net_monthly_income;
   }

   public java.lang.Double getCoapplicant_net_monthly_income()
   {
      return this.coapplicant_net_monthly_income;
   }

   public void setCoapplicant_net_monthly_income(
         java.lang.Double coapplicant_net_monthly_income)
   {
      this.coapplicant_net_monthly_income = coapplicant_net_monthly_income;
   }

   public java.lang.Double getCoapplicant_net_servicibility()
   {
      return this.coapplicant_net_servicibility;
   }

   public void setCoapplicant_net_servicibility(
         java.lang.Double coapplicant_net_servicibility)
   {
      this.coapplicant_net_servicibility = coapplicant_net_servicibility;
   }

   public java.lang.Double getCoapplicant_cibil_total_obligations_considered()
   {
      return this.coapplicant_cibil_total_obligations_considered;
   }

   public void setCoapplicant_cibil_total_obligations_considered(
         java.lang.Double coapplicant_cibil_total_obligations_considered)
   {
      this.coapplicant_cibil_total_obligations_considered = coapplicant_cibil_total_obligations_considered;
   }

   public java.util.List<java.lang.Integer> getLoan_multiplier_list()
   {
      return this.loan_multiplier_list;
   }

   public void setLoan_multiplier_list(
         java.util.List<java.lang.Integer> loan_multiplier_list)
   {
      this.loan_multiplier_list = loan_multiplier_list;
   }

   public java.lang.Integer getApplicant_residence_type()
   {
      return this.applicant_residence_type;
   }

   public void setApplicant_residence_type(
         java.lang.Integer applicant_residence_type)
   {
      this.applicant_residence_type = applicant_residence_type;
   }

   public java.lang.Integer getApplicant_pa_location_type()
   {
      return this.applicant_pa_location_type;
   }

   public void setApplicant_pa_location_type(
         java.lang.Integer applicant_pa_location_type)
   {
      this.applicant_pa_location_type = applicant_pa_location_type;
   }

   public java.lang.Integer getApplicant_cibil_live_track_pl_al_hl()
   {
      return this.applicant_cibil_live_track_pl_al_hl;
   }

   public void setApplicant_cibil_live_track_pl_al_hl(
         java.lang.Integer applicant_cibil_live_track_pl_al_hl)
   {
      this.applicant_cibil_live_track_pl_al_hl = applicant_cibil_live_track_pl_al_hl;
   }

   public java.lang.Double getApplicant_max_age_allowed()
   {
      return this.applicant_max_age_allowed;
   }

   public void setApplicant_max_age_allowed(
         java.lang.Double applicant_max_age_allowed)
   {
      this.applicant_max_age_allowed = applicant_max_age_allowed;
   }

   public java.lang.Double getApplicant_net_servicibility()
   {
      return this.applicant_net_servicibility;
   }

   public void setApplicant_net_servicibility(
         java.lang.Double applicant_net_servicibility)
   {
      this.applicant_net_servicibility = applicant_net_servicibility;
   }

   public java.lang.Integer getApplicant_cibil_overdue()
   {
      return this.applicant_cibil_overdue;
   }

   public void setApplicant_cibil_overdue(java.lang.Integer applicant_cibil_overdue)
   {
      this.applicant_cibil_overdue = applicant_cibil_overdue;
   }

   public java.util.Date getTest_date()
   {
      return this.test_date;
   }

   public void setTest_date(java.util.Date test_date)
   {
      this.test_date = test_date;
   }

   public java.util.Date getTest_from_date()
   {
      return this.test_from_date;
   }

   public void setTest_from_date(java.util.Date test_from_date)
   {
      this.test_from_date = test_from_date;
   }

   public java.lang.Integer getApplicant_cibil_total_inquiries()
   {
      return this.applicant_cibil_total_inquiries;
   }

   public void setApplicant_cibil_total_inquiries(
         java.lang.Integer applicant_cibil_total_inquiries)
   {
      this.applicant_cibil_total_inquiries = applicant_cibil_total_inquiries;
   }

   public java.lang.Integer getApplicant_cibil_writtenoff_accounts()
   {
      return this.applicant_cibil_writtenoff_accounts;
   }

   public void setApplicant_cibil_writtenoff_accounts(
         java.lang.Integer applicant_cibil_writtenoff_accounts)
   {
      this.applicant_cibil_writtenoff_accounts = applicant_cibil_writtenoff_accounts;
   }

   public java.lang.Integer getApplicant_cibil_settled_accounts()
   {
      return this.applicant_cibil_settled_accounts;
   }

   public void setApplicant_cibil_settled_accounts(
         java.lang.Integer applicant_cibil_settled_accounts)
   {
      this.applicant_cibil_settled_accounts = applicant_cibil_settled_accounts;
   }

   public java.lang.Double getApplicant_cibil_settled_amount()
   {
      return this.applicant_cibil_settled_amount;
   }

   public void setApplicant_cibil_settled_amount(
         java.lang.Double applicant_cibil_settled_amount)
   {
      this.applicant_cibil_settled_amount = applicant_cibil_settled_amount;
   }

   public java.lang.Double getApplicant_cibil_writtenoff_amount()
   {
      return this.applicant_cibil_writtenoff_amount;
   }

   public void setApplicant_cibil_writtenoff_amount(
         java.lang.Double applicant_cibil_writtenoff_amount)
   {
      this.applicant_cibil_writtenoff_amount = applicant_cibil_writtenoff_amount;
   }

   public java.lang.Double getApplicant_cibil_cc_outstanding_amount()
   {
      return this.applicant_cibil_cc_outstanding_amount;
   }

   public void setApplicant_cibil_cc_outstanding_amount(
         java.lang.Double applicant_cibil_cc_outstanding_amount)
   {
      this.applicant_cibil_cc_outstanding_amount = applicant_cibil_cc_outstanding_amount;
   }

   public Applicant(java.lang.Integer applicant_education_qualification,
         java.lang.Double applicant_age, char applicant_employment_is_permanent,
         java.lang.Integer applicant_total_work_ex,
         java.lang.Integer applicant_cibil_score_v2,
         java.lang.String applicant_dob,
         java.lang.Double applicant_age_at_maturity,
         java.lang.Integer applicant_company_category,
         java.lang.Double applicant_income,
         java.lang.Integer applicant_residential_status,
         java.lang.Double applicant_foir,
         java.lang.Double applicant_cibil_total_obligations,
         java.lang.Double applicant_cibil_total_obligations_considered,
         java.lang.Double applicant_net_servicibility,
         java.lang.Double applicant_combined_net_monthly_income,
         java.lang.Double coapplicant_net_monthly_income,
         java.lang.Double coapplicant_foir,
         java.lang.Double coapplicant_net_servicibility,
         java.lang.Double coapplicant_cibil_total_obligations_considered,
         java.lang.Integer applicant_cibil_live_pl_accounts,
         java.lang.Integer applicant_cibil_pl_inquiries,
         java.lang.Integer applicant_company_industry_type,
         java.lang.Double applicant_abb,
         java.util.List<java.lang.Integer> loan_multiplier_list,
         java.lang.Integer applicant_residence_type,
         java.lang.Integer applicant_pa_location_type,
         java.lang.Integer applicant_cibil_live_track_pl_al_hl,
         java.lang.Double applicant_max_age_allowed,
         java.lang.Integer applicant_cibil_overdue, java.util.Date test_date,
         java.util.Date test_from_date,
         java.lang.Integer applicant_cibil_total_inquiries,
         java.lang.Integer applicant_cibil_writtenoff_accounts,
         java.lang.Integer applicant_cibil_settled_accounts,
         java.lang.Double applicant_cibil_settled_amount,
         java.lang.Double applicant_cibil_writtenoff_amount,
         java.lang.Double applicant_cibil_cc_outstanding_amount)
   {
      this.applicant_education_qualification = applicant_education_qualification;
      this.applicant_age = applicant_age;
      this.applicant_employment_is_permanent = applicant_employment_is_permanent;
      this.applicant_total_work_ex = applicant_total_work_ex;
      this.applicant_cibil_score_v2 = applicant_cibil_score_v2;
      this.applicant_dob = applicant_dob;
      this.applicant_age_at_maturity = applicant_age_at_maturity;
      this.applicant_company_category = applicant_company_category;
      this.applicant_income = applicant_income;
      this.applicant_residential_status = applicant_residential_status;
      this.applicant_foir = applicant_foir;
      this.applicant_cibil_total_obligations = applicant_cibil_total_obligations;
      this.applicant_cibil_total_obligations_considered = applicant_cibil_total_obligations_considered;
      this.applicant_net_servicibility = applicant_net_servicibility;
      this.applicant_combined_net_monthly_income = applicant_combined_net_monthly_income;
      this.coapplicant_net_monthly_income = coapplicant_net_monthly_income;
      this.coapplicant_foir = coapplicant_foir;
      this.coapplicant_net_servicibility = coapplicant_net_servicibility;
      this.coapplicant_cibil_total_obligations_considered = coapplicant_cibil_total_obligations_considered;
      this.applicant_cibil_live_pl_accounts = applicant_cibil_live_pl_accounts;
      this.applicant_cibil_pl_inquiries = applicant_cibil_pl_inquiries;
      this.applicant_company_industry_type = applicant_company_industry_type;
      this.applicant_abb = applicant_abb;
      this.loan_multiplier_list = loan_multiplier_list;
      this.applicant_residence_type = applicant_residence_type;
      this.applicant_pa_location_type = applicant_pa_location_type;
      this.applicant_cibil_live_track_pl_al_hl = applicant_cibil_live_track_pl_al_hl;
      this.applicant_max_age_allowed = applicant_max_age_allowed;
      this.applicant_cibil_overdue = applicant_cibil_overdue;
      this.test_date = test_date;
      this.test_from_date = test_from_date;
      this.applicant_cibil_total_inquiries = applicant_cibil_total_inquiries;
      this.applicant_cibil_writtenoff_accounts = applicant_cibil_writtenoff_accounts;
      this.applicant_cibil_settled_accounts = applicant_cibil_settled_accounts;
      this.applicant_cibil_settled_amount = applicant_cibil_settled_amount;
      this.applicant_cibil_writtenoff_amount = applicant_cibil_writtenoff_amount;
      this.applicant_cibil_cc_outstanding_amount = applicant_cibil_cc_outstanding_amount;
   }

}
