package personalloan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinalResult implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Integer app_xml_tu_status_id;

   public FinalResult()
   {
   }

   public java.lang.Integer getApp_xml_tu_status_id()
   {
      return this.app_xml_tu_status_id;
   }

   public void setApp_xml_tu_status_id(java.lang.Integer app_xml_tu_status_id)
   {
      this.app_xml_tu_status_id = app_xml_tu_status_id;
   }

   public FinalResult(java.lang.Integer app_xml_tu_status_id)
   {
      this.app_xml_tu_status_id = app_xml_tu_status_id;
   }

}
