package personalloan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Guarantor implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Guarantor() {
    }

}
