package personalloan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RepaymentSchedule implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer month;
   private java.lang.Integer starting_out_standing_loan_amount;
   private java.lang.Integer interest;
   private java.lang.Integer EMI;
   private java.lang.Integer ending_out_standing_loan_amount;

   public RepaymentSchedule()
   {
   }

   public java.lang.Integer getMonth()
   {
      return this.month;
   }

   public void setMonth(java.lang.Integer month)
   {
      this.month = month;
   }

   public java.lang.Integer getStarting_out_standing_loan_amount()
   {
      return this.starting_out_standing_loan_amount;
   }

   public void setStarting_out_standing_loan_amount(
         java.lang.Integer starting_out_standing_loan_amount)
   {
      this.starting_out_standing_loan_amount = starting_out_standing_loan_amount;
   }

   public java.lang.Integer getInterest()
   {
      return this.interest;
   }

   public void setInterest(java.lang.Integer interest)
   {
      this.interest = interest;
   }

   public java.lang.Integer getEMI()
   {
      return this.EMI;
   }

   public void setEMI(java.lang.Integer EMI)
   {
      this.EMI = EMI;
   }

   public java.lang.Integer getEnding_out_standing_loan_amount()
   {
      return this.ending_out_standing_loan_amount;
   }

   public void setEnding_out_standing_loan_amount(
         java.lang.Integer ending_out_standing_loan_amount)
   {
      this.ending_out_standing_loan_amount = ending_out_standing_loan_amount;
   }

   public RepaymentSchedule(java.lang.Integer month,
         java.lang.Integer starting_out_standing_loan_amount,
         java.lang.Integer interest, java.lang.Integer EMI,
         java.lang.Integer ending_out_standing_loan_amount)
   {
      this.month = month;
      this.starting_out_standing_loan_amount = starting_out_standing_loan_amount;
      this.interest = interest;
      this.EMI = EMI;
      this.ending_out_standing_loan_amount = ending_out_standing_loan_amount;
   }

}
