package personalloan;
import java.lang.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleResults implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Integer rule_Id;
   private java.lang.String rule_Description;
   private java.lang.String cut_off_value;
   private java.lang.String actual_Value;

   private java.lang.Integer system_Decision;

   private java.lang.Integer deviation_Level;

   private personalloan.Variables variables;

   public RuleResults()
   {
   }

   public java.lang.String getRule_Description()
   {
      return this.rule_Description;
   }

   public void setRule_Description(java.lang.String rule_Description)
   {
      this.rule_Description = rule_Description;
   }

   public java.lang.String getCut_off_value()
   {
      return this.cut_off_value;
   }

   public void setCut_off_value(java.lang.String cut_off_value)
   {
      this.cut_off_value = cut_off_value;
   }

   public java.lang.Integer getRule_Id()
   {
      return this.rule_Id;
   }

   public void setRule_Id(java.lang.Integer rule_Id)
   {
      this.rule_Id = rule_Id;
   }

   public java.lang.Integer getSystem_Decision()
   {
      return this.system_Decision;
   }

   public void setSystem_Decision(java.lang.Integer system_Decision)
   {
      this.system_Decision = system_Decision;
   }

   public java.lang.Integer getDeviation_Level()
   {
      return this.deviation_Level;
   }

   public void setDeviation_Level(java.lang.Integer deviation_Level)
   {
      this.deviation_Level = deviation_Level;
   }

   public java.lang.String getActual_Value()
   {
      return this.actual_Value;
   }

   public void setActual_Value(java.lang.String actual_Value)
   {
      this.actual_Value = actual_Value;
   }

   public personalloan.Variables getVariables()
   {
      return this.variables;
   }

   public void setVariables(personalloan.Variables variables)
   {
      this.variables = variables;
   }

   public RuleResults(java.lang.Integer rule_Id,
         java.lang.String rule_Description, java.lang.String cut_off_value,
         java.lang.String actual_Value, java.lang.Integer system_Decision,
         java.lang.Integer deviation_Level,
         personalloan.Variables variables)
   {
      this.rule_Id = rule_Id;
      this.rule_Description = rule_Description;
      this.cut_off_value = cut_off_value;
      this.actual_Value = actual_Value;
      this.system_Decision = system_Decision;
      this.deviation_Level = deviation_Level;
      this.variables = variables;
   }

}
