package personalloan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Variables implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String DOB;

   private java.lang.Integer highest_Educational_Qualification;

   private java.lang.Integer app_CIBIL_Score;

   private java.lang.String total_work_experience;

   private java.lang.String current_age;

   private java.lang.String considered_Tenure;

   private java.lang.Integer max_Multiplier;

   private java.lang.Integer EMI_Loan_Applied;

   private java.lang.Integer app_Net_Monthly_Income;

   private java.lang.Integer EMI_from_obligations_app;

   private java.lang.Double debt_Ratio_App;

   private java.lang.Integer serviceability_App;

   private java.lang.Integer rental_Expense;

   private java.lang.Integer coapp_Net_Monthly_Income;

   private java.lang.Integer EMI_from_obligations_co_app;

   private Double debt_Ratio_Co_app;

   private java.lang.Integer serviceability_Co_app;

   private java.lang.Integer number_of_current_PL;

   private java.lang.Integer enquiries_month_in_last_1_month;

   private java.lang.Integer product_Cap_loan_amount;

   private java.lang.Integer average_Bank_Balance;

   private java.lang.Integer loan_Applied;

   private java.lang.Integer system_Approved;

   private java.lang.Integer loan_Eligible;

   private java.lang.Integer net_Monthly_Income;

   private java.lang.Integer combined_Net_Monthly_Income;

   private java.lang.Integer tenure_Applied;

   private java.lang.Integer max_Tenure;

   private java.lang.Integer tenure_Eligible;

   private java.lang.Integer overdue;

   public Variables()
   {
   }

   public java.lang.Integer getHighest_Educational_Qualification()
   {
      return this.highest_Educational_Qualification;
   }

   public void setHighest_Educational_Qualification(
         java.lang.Integer highest_Educational_Qualification)
   {
      this.highest_Educational_Qualification = highest_Educational_Qualification;
   }

   public java.lang.String getDOB()
   {
      return this.DOB;
   }

   public void setDOB(java.lang.String DOB)
   {
      this.DOB = DOB;
   }

   public java.lang.Integer getApp_CIBIL_Score()
   {
      return this.app_CIBIL_Score;
   }

   public void setApp_CIBIL_Score(java.lang.Integer app_CIBIL_Score)
   {
      this.app_CIBIL_Score = app_CIBIL_Score;
   }

   public java.lang.String getTotal_work_experience()
   {
      return this.total_work_experience;
   }

   public void setTotal_work_experience(java.lang.String total_work_experience)
   {
      this.total_work_experience = total_work_experience;
   }

   public java.lang.String getCurrent_age()
   {
      return this.current_age;
   }

   public void setCurrent_age(java.lang.String current_age)
   {
      this.current_age = current_age;
   }

   public java.lang.String getConsidered_Tenure()
   {
      return this.considered_Tenure;
   }

   public void setConsidered_Tenure(java.lang.String considered_Tenure)
   {
      this.considered_Tenure = considered_Tenure;
   }

   public java.lang.Integer getMax_Multiplier()
   {
      return this.max_Multiplier;
   }

   public void setMax_Multiplier(java.lang.Integer max_Multiplier)
   {
      this.max_Multiplier = max_Multiplier;
   }

   public java.lang.Integer getEMI_Loan_Applied()
   {
      return this.EMI_Loan_Applied;
   }

   public void setEMI_Loan_Applied(java.lang.Integer EMI_Loan_Applied)
   {
      this.EMI_Loan_Applied = EMI_Loan_Applied;
   }

   public java.lang.Integer getApp_Net_Monthly_Income()
   {
      return this.app_Net_Monthly_Income;
   }

   public void setApp_Net_Monthly_Income(java.lang.Integer app_Net_Monthly_Income)
   {
      this.app_Net_Monthly_Income = app_Net_Monthly_Income;
   }

   public java.lang.Integer getEMI_from_obligations_app()
   {
      return this.EMI_from_obligations_app;
   }

   public void setEMI_from_obligations_app(
         java.lang.Integer EMI_from_obligations_app)
   {
      this.EMI_from_obligations_app = EMI_from_obligations_app;
   }

   public java.lang.Double getDebt_Ratio_App()
   {
      return this.debt_Ratio_App;
   }

   public void setDebt_Ratio_App(java.lang.Double debt_Ratio_App)
   {
      this.debt_Ratio_App = debt_Ratio_App;
   }

   public java.lang.Integer getServiceability_App()
   {
      return this.serviceability_App;
   }

   public void setServiceability_App(java.lang.Integer serviceability_App)
   {
      this.serviceability_App = serviceability_App;
   }

   public java.lang.Integer getRental_Expense()
   {
      return this.rental_Expense;
   }

   public void setRental_Expense(java.lang.Integer rental_Expense)
   {
      this.rental_Expense = rental_Expense;
   }

   public java.lang.Integer getCoapp_Net_Monthly_Income()
   {
      return this.coapp_Net_Monthly_Income;
   }

   public void setCoapp_Net_Monthly_Income(
         java.lang.Integer coapp_Net_Monthly_Income)
   {
      this.coapp_Net_Monthly_Income = coapp_Net_Monthly_Income;
   }

   public java.lang.Integer getEMI_from_obligations_co_app()
   {
      return this.EMI_from_obligations_co_app;
   }

   public void setEMI_from_obligations_co_app(
         java.lang.Integer EMI_from_obligations_co_app)
   {
      this.EMI_from_obligations_co_app = EMI_from_obligations_co_app;
   }

   public java.lang.Integer getServiceability_Co_app()
   {
      return this.serviceability_Co_app;
   }

   public void setServiceability_Co_app(java.lang.Integer serviceability_Co_app)
   {
      this.serviceability_Co_app = serviceability_Co_app;
   }

   public java.lang.Integer getNumber_of_current_PL()
   {
      return this.number_of_current_PL;
   }

   public void setNumber_of_current_PL(java.lang.Integer number_of_current_PL)
   {
      this.number_of_current_PL = number_of_current_PL;
   }

   public java.lang.Integer getEnquiries_month_in_last_1_month()
   {
      return this.enquiries_month_in_last_1_month;
   }

   public void setEnquiries_month_in_last_1_month(
         java.lang.Integer enquiries_month_in_last_1_month)
   {
      this.enquiries_month_in_last_1_month = enquiries_month_in_last_1_month;
   }

   public java.lang.Integer getProduct_Cap_loan_amount()
   {
      return this.product_Cap_loan_amount;
   }

   public void setProduct_Cap_loan_amount(java.lang.Integer product_Cap_loan_amount)
   {
      this.product_Cap_loan_amount = product_Cap_loan_amount;
   }

   public java.lang.Integer getAverage_Bank_Balance()
   {
      return this.average_Bank_Balance;
   }

   public void setAverage_Bank_Balance(java.lang.Integer average_Bank_Balance)
   {
      this.average_Bank_Balance = average_Bank_Balance;
   }

   public java.lang.Integer getLoan_Applied()
   {
      return this.loan_Applied;
   }

   public void setLoan_Applied(java.lang.Integer loan_Applied)
   {
      this.loan_Applied = loan_Applied;
   }

   public java.lang.Integer getSystem_Approved()
   {
      return this.system_Approved;
   }

   public void setSystem_Approved(java.lang.Integer system_Approved)
   {
      this.system_Approved = system_Approved;
   }

   public java.lang.Integer getLoan_Eligible()
   {
      return this.loan_Eligible;
   }

   public void setLoan_Eligible(java.lang.Integer loan_Eligible)
   {
      this.loan_Eligible = loan_Eligible;
   }

   public java.lang.Double getDebt_Ratio_Co_app()
   {
      return this.debt_Ratio_Co_app;
   }

   public void setDebt_Ratio_Co_app(java.lang.Double debt_Ratio_Co_app)
   {
      this.debt_Ratio_Co_app = debt_Ratio_Co_app;
   }

   public java.lang.Integer getNet_Monthly_Income()
   {
      return this.net_Monthly_Income;
   }

   public void setNet_Monthly_Income(java.lang.Integer net_Monthly_Income)
   {
      this.net_Monthly_Income = net_Monthly_Income;
   }

   public java.lang.Integer getCombined_Net_Monthly_Income()
   {
      return this.combined_Net_Monthly_Income;
   }

   public void setCombined_Net_Monthly_Income(
         java.lang.Integer combined_Net_Monthly_Income)
   {
      this.combined_Net_Monthly_Income = combined_Net_Monthly_Income;
   }

   public java.lang.Integer getTenure_Applied()
   {
      return this.tenure_Applied;
   }

   public void setTenure_Applied(java.lang.Integer tenure_Applied)
   {
      this.tenure_Applied = tenure_Applied;
   }

   public java.lang.Integer getMax_Tenure()
   {
      return this.max_Tenure;
   }

   public void setMax_Tenure(java.lang.Integer max_Tenure)
   {
      this.max_Tenure = max_Tenure;
   }

   public java.lang.Integer getTenure_Eligible()
   {
      return this.tenure_Eligible;
   }

   public void setTenure_Eligible(java.lang.Integer tenure_Eligible)
   {
      this.tenure_Eligible = tenure_Eligible;
   }

   public java.lang.Integer getOverdue()
   {
      return this.overdue;
   }

   public void setOverdue(java.lang.Integer overdue)
   {
      this.overdue = overdue;
   }

   public Variables(java.lang.String DOB,
         java.lang.Integer highest_Educational_Qualification,
         java.lang.Integer app_CIBIL_Score,
         java.lang.String total_work_experience, java.lang.String current_age,
         java.lang.String considered_Tenure, java.lang.Integer max_Multiplier,
         java.lang.Integer EMI_Loan_Applied,
         java.lang.Integer app_Net_Monthly_Income,
         java.lang.Integer EMI_from_obligations_app,
         java.lang.Double debt_Ratio_App, java.lang.Integer serviceability_App,
         java.lang.Integer rental_Expense,
         java.lang.Integer coapp_Net_Monthly_Income,
         java.lang.Integer EMI_from_obligations_co_app,
         java.lang.Double debt_Ratio_Co_app,
         java.lang.Integer serviceability_Co_app,
         java.lang.Integer number_of_current_PL,
         java.lang.Integer enquiries_month_in_last_1_month,
         java.lang.Integer product_Cap_loan_amount,
         java.lang.Integer average_Bank_Balance, java.lang.Integer loan_Applied,
         java.lang.Integer system_Approved, java.lang.Integer loan_Eligible,
         java.lang.Integer net_Monthly_Income,
         java.lang.Integer combined_Net_Monthly_Income,
         java.lang.Integer tenure_Applied, java.lang.Integer max_Tenure,
         java.lang.Integer tenure_Eligible, java.lang.Integer overdue)
   {
      this.DOB = DOB;
      this.highest_Educational_Qualification = highest_Educational_Qualification;
      this.app_CIBIL_Score = app_CIBIL_Score;
      this.total_work_experience = total_work_experience;
      this.current_age = current_age;
      this.considered_Tenure = considered_Tenure;
      this.max_Multiplier = max_Multiplier;
      this.EMI_Loan_Applied = EMI_Loan_Applied;
      this.app_Net_Monthly_Income = app_Net_Monthly_Income;
      this.EMI_from_obligations_app = EMI_from_obligations_app;
      this.debt_Ratio_App = debt_Ratio_App;
      this.serviceability_App = serviceability_App;
      this.rental_Expense = rental_Expense;
      this.coapp_Net_Monthly_Income = coapp_Net_Monthly_Income;
      this.EMI_from_obligations_co_app = EMI_from_obligations_co_app;
      this.debt_Ratio_Co_app = debt_Ratio_Co_app;
      this.serviceability_Co_app = serviceability_Co_app;
      this.number_of_current_PL = number_of_current_PL;
      this.enquiries_month_in_last_1_month = enquiries_month_in_last_1_month;
      this.product_Cap_loan_amount = product_Cap_loan_amount;
      this.average_Bank_Balance = average_Bank_Balance;
      this.loan_Applied = loan_Applied;
      this.system_Approved = system_Approved;
      this.loan_Eligible = loan_Eligible;
      this.net_Monthly_Income = net_Monthly_Income;
      this.combined_Net_Monthly_Income = combined_Net_Monthly_Income;
      this.tenure_Applied = tenure_Applied;
      this.max_Tenure = max_Tenure;
      this.tenure_Eligible = tenure_Eligible;
      this.overdue = overdue;
   }

}
